### PR TITLE
generalize chain to allow any iterable of iterables

### PR DESCRIPTION
**Pull request by Futrell**
I rewrote the chain iterator so that the Chain object stores an iterator of iterators, rather than a vector of iterators. This means that it doesn't force evaluation of the iterator-of-iterators when the chain is created. (I needed this lazy behavior for a project I was working on.)

To do this I changed the constructor for the Chain type (but the interface of lowercase chain is unchanged), and I added chain_from_iterable, named after Python's itertools.chain.from_iterable. If changing the constructor of Chain is bad, I could make this work by making a ChainFromIterable type or something instead.

Product could also be rewritten to be lazy in this way.

hope this is useful.

### CODE REVIEW

**Comment by kmsquire** [comment]
Looks like this PR was forgotten (I ran across it randomly).

Answering @StefanKarpinski's last question, given that the performance of this version is better (should be checked), I don't see any reason `chain` couldn't always be lazy.

@Futrell, it's been a while, but would you be able to rebase this on the current master?

**Comment by Futrell** [comment]
OK, I rebased. I went with the name ``flat`` for the version of Chain that accepts one iterable argument. This way, ``flat(map(f, xs))`` in Julia means the same thing as ``flatmap(f, xs)`` in several other languages.

The lazy Chain implementation is still faster than the old array-based one on the benchmarks in ``test/perf.jl``, moreso than a year ago. It looks like the old array-based Chain got a lot slower. This is on 0.4.0-dev+6559 today on a Macbook Pro i7. 

config  |   Chain | new Chain 
---------|--------------- |------
4096    |     3.9063 | 1.0988
16384   |     14.8271 | 4.1187 
65536   |   59.4780 | 16.4696 
262144  |  237.3013 | 69.9872 
1048576 | 945.0631 |  260.1893

**Comment by kmsquire** [comment]
I'll take a closer look later, but I think that my preference is for this to actually replace the chain function.

**Comment by Krastanov** [comment]
Given that there is IterTools now, does it mean that this pull request will not be accepted? Having this would be pretty useful...

**Comment by Krastanov** [comment]
Or maybe I am just misunderstanding IterTools... Does this line https://github.com/JuliaCollections/IterTools.jl/blob/master/src/IterTools.jl#L181 mean that this is already implemented there?

**Comment by kmsquire** [comment]
Hi @Krastanov, it does look like Chain was changed to something close to this PR. Thanks for poking at it.

**Comment by Krastanov** [comment]
I think I was wrong though... Chain underperforms on the cases made here, mainly because the splatting is executed anyway. I will open a new issue about it.

**Comment by iamed2** [comment]
It is not already implemented in IterTools, however this now exists in Base as `Iterators.flatten`

**Pull request closed without merging**
