### PR TITLE
Migration of iterators to Base, and sync with 0.4 syntax

### PR DESCRIPTION
**Pull request by garborg**
Migration as of: https://github.com/JuliaLang/julia/commit/7a8f434be147b86fa73a3bde74f6c75d5749e090

### CODE REVIEW

**Comment by garborg** [comment]
(Passed locally on master and release-0.3, with deprecation warnings in only the right places on both (groupby and sometimes count).)

**Comment by garborg** [comment]
Bump.

The one other bit of work I could see doing is deprecating `count` in favor of `countfrom` on 0.3 as well, but that could also come later.

**Comment by garborg** [comment]
Unless it would be better to move all the now-Base iterators completely out of here, to Compat. And have this just use Compat? That seems better to me.

**Comment by jiahao** [comment]
Let's have the test failure on 0.4 fixed and we can just merge it in without dawdling about where the code should go.

https://travis-ci.org/JuliaLang/Iterators.jl/jobs/50714323#L235

**Pull request merged**
